from app.content.script_generator import build_summary, generate_script


def test_no_summary_falls_back_to_placeholder():
    assert build_summary(None) == "No summary was available from the source."
    assert build_summary("") == "No summary was available from the source."


def test_strips_html_tags_and_entities():
    summary = build_summary("<p>OpenAI &amp; friends ship a model.</p>")
    assert "<p>" not in summary
    assert "&amp;" not in summary
    assert "OpenAI & friends ship a model." in summary


def test_truncation_marker_is_dropped():
    """
    Regression for the "summary trails off mid-thought" bug: a feed's
    own excerpt-cutoff ellipsis must not be read aloud as if it were a
    complete sentence.
    """
    summary = build_summary(
        "The company announced a new product. It will ship next year. "
        "The team is also signing on to a […]"
    )
    assert "[…]" not in summary
    assert summary.endswith("It will ship next year.")


def test_promo_sentence_is_dropped():
    """
    Regression for the "sign up here" bug found via live audit this
    session -- a newsletter-pitch sentence must not appear in the
    narrated summary.
    """
    summary = build_summary(
        "This weekend, Dario Amodei posted an essay calling for a brake "
        "on AI development. To get stories like this in your inbox "
        "first, sign up here."
    )
    assert "sign up" not in summary.lower()
    assert "Dario Amodei" in summary


def test_promo_sentence_variants_all_dropped():
    for phrase in [
        "Subscribe to our YouTube channel for more videos.",
        "Log in to read the rest of this article.",
        "Sign in with your account to continue.",
        "Check out our newsletter for weekly updates.",
    ]:
        summary = build_summary(f"Real content here. {phrase}")
        assert phrase not in summary
        assert "Real content here." in summary


def test_all_sentences_promotional_falls_back_to_placeholder():
    """
    If filtering out promo sentences leaves nothing real (the story
    #39 case from this session's audit -- the entire fetched page was
    a subscription pitch), the honest "no summary" fallback is correct,
    not an empty string.
    """
    summary = build_summary("Subscribe to my premium newsletter for $70 a year.")
    assert summary == "No summary was available from the source."


def test_summary_truncates_to_max_sentences():
    raw = "One. Two. Three. Four. Five."
    summary = build_summary(raw, max_sentences=2)
    assert summary == "One. Two."


def test_sentence_split_handles_a_closing_quote_after_the_period():
    """
    Real bug found live via the raw_content full-article-scraping
    feature: a period immediately followed by a closing curly quote
    (”), with no whitespace between them, must still count as a
    sentence boundary -- otherwise everything up to the NEXT period
    silently merges into one oversized "sentence", defeating
    MAX_SUMMARY_SENTENCES for any text with quoted speech (rare in RSS
    excerpts, routine in real news prose). The closing quote itself
    must also be preserved on the sentence it closes, not dropped.
    """
    text = (
        'He said these concerns are hoaxes “generated by the opposition, '
        'for purposes of destroying our Country.” On Saturday, he continued '
        "his remarks on social media."
    )
    summary = build_summary(text, max_sentences=1)
    assert summary == (
        'He said these concerns are hoaxes “generated by the opposition, '
        'for purposes of destroying our Country.”'
    )
    assert "On Saturday" not in summary


def test_generate_script_combines_headline_and_summary():
    result = generate_script(title="  Big AI News  ", raw_summary="Something happened.")
    assert result["headline"] == "Big AI News"
    assert result["summary"] == "Something happened."
    assert result["script_text"] == "Big AI News. Something happened."


def test_generate_script_normalizes_whitespace():
    result = generate_script(title="Title", raw_summary="Line one.\n\nLine  two.")
    assert "\n" not in result["script_text"]
    assert "  " not in result["script_text"]


# ---------------------------------------------------------------------
# raw_content (full extracted article body -- see
# app/content/article_extractor.py, populated by app/tasks/content_dedup.py)
# preferred over raw_summary (RSS's often thin/truncated/promotional
# excerpt) when present, with a graceful fallback otherwise.
# ---------------------------------------------------------------------

def test_generate_script_prefers_raw_content_over_raw_summary():
    result = generate_script(
        title="Big AI News",
        raw_summary="A thin RSS excerpt that gets cut off […]",
        raw_content="The real article opens with this full sentence. It continues here.",
    )
    assert result["summary"] == "The real article opens with this full sentence. It continues here."
    assert "thin RSS excerpt" not in result["summary"]
    # headline always comes from title, regardless of source text.
    assert result["headline"] == "Big AI News"


def test_generate_script_falls_back_to_raw_summary_when_raw_content_is_none():
    result = generate_script(title="Title", raw_summary="Only the RSS excerpt exists.", raw_content=None)
    assert result["summary"] == "Only the RSS excerpt exists."


def test_generate_script_falls_back_to_raw_summary_when_raw_content_is_blank():
    """Defensive: shouldn't happen given article_extractor.py's own
    MIN_CONTENT_CHARS gate before raw_content is ever persisted, but an
    empty/whitespace-only value must not be mistaken for real content."""
    result = generate_script(title="Title", raw_summary="The RSS excerpt.", raw_content="   ")
    assert result["summary"] == "The RSS excerpt."


def test_generate_script_with_only_raw_content_and_no_raw_summary():
    result = generate_script(title="Title", raw_summary=None, raw_content="The full article body text.")
    assert result["summary"] == "The full article body text."


def test_full_article_body_gets_the_same_hygiene_and_sentence_cap():
    """The existing summarizer's behavior (HTML-strip, promo-sentence-
    drop, truncation-marker-drop, MAX_SUMMARY_SENTENCES cap) must
    generalize correctly to a longer, real full-article body, not just
    short RSS excerpts."""
    article_body = (
        "<p>The company announced a major new model today.</p> "
        "It supports twice the context length of its predecessor. "
        "Early benchmarks show meaningful gains on reasoning tasks. "
        "Pricing will be announced next quarter. "
        "Subscribe to our newsletter for the full breakdown."
    )
    result = generate_script(title="Title", raw_summary="short excerpt", raw_content=article_body)
    assert "<p>" not in result["summary"]
    assert "newsletter" not in result["summary"].lower()
    # MAX_SUMMARY_SENTENCES default is 3 -- only the first 3 real
    # (non-promotional) sentences survive.
    assert result["summary"] == (
        "The company announced a major new model today. "
        "It supports twice the context length of its predecessor. "
        "Early benchmarks show meaningful gains on reasoning tasks."
    )
