from app.content.script_generator import build_summary, generate_script


def test_no_summary_falls_back_to_placeholder():
    assert build_summary(None) == "No summary was available from the source."
    assert build_summary("") == "No summary was available from the source."


def test_strips_html_tags_and_entities():
    summary = build_summary("<p>OpenAI &amp; friends ship a model.</p>")
    assert "<p>" not in summary
    assert "&amp;" not in summary
    assert "OpenAI & friends ship a model." in summary


def test_truncation_marker_is_dropped():
    """
    Regression for the "summary trails off mid-thought" bug: a feed's
    own excerpt-cutoff ellipsis must not be read aloud as if it were a
    complete sentence.
    """
    summary = build_summary(
        "The company announced a new product. It will ship next year. "
        "The team is also signing on to a […]"
    )
    assert "[…]" not in summary
    assert summary.endswith("It will ship next year.")


def test_promo_sentence_is_dropped():
    """
    Regression for the "sign up here" bug found via live audit this
    session -- a newsletter-pitch sentence must not appear in the
    narrated summary.
    """
    summary = build_summary(
        "This weekend, Dario Amodei posted an essay calling for a brake "
        "on AI development. To get stories like this in your inbox "
        "first, sign up here."
    )
    assert "sign up" not in summary.lower()
    assert "Dario Amodei" in summary


def test_promo_sentence_variants_all_dropped():
    for phrase in [
        "Subscribe to our YouTube channel for more videos.",
        "Log in to read the rest of this article.",
        "Sign in with your account to continue.",
        "Check out our newsletter for weekly updates.",
    ]:
        summary = build_summary(f"Real content here. {phrase}")
        assert phrase not in summary
        assert "Real content here." in summary


def test_all_sentences_promotional_falls_back_to_placeholder():
    """
    If filtering out promo sentences leaves nothing real (the story
    #39 case from this session's audit -- the entire fetched page was
    a subscription pitch), the honest "no summary" fallback is correct,
    not an empty string.
    """
    summary = build_summary("Subscribe to my premium newsletter for $70 a year.")
    assert summary == "No summary was available from the source."


def test_summary_truncates_to_max_sentences():
    raw = "One. Two. Three. Four. Five."
    summary = build_summary(raw, max_sentences=2)
    assert summary == "One. Two."


def test_sentence_split_handles_a_closing_quote_after_the_period():
    """
    Real bug found live via the raw_content full-article-scraping
    feature: a period immediately followed by a closing curly quote
    (”), with no whitespace between them, must still count as a
    sentence boundary -- otherwise everything up to the NEXT period
    silently merges into one oversized "sentence", defeating
    MAX_SUMMARY_SENTENCES for any text with quoted speech (rare in RSS
    excerpts, routine in real news prose). The closing quote itself
    must also be preserved on the sentence it closes, not dropped.
    """
    text = (
        'He said these concerns are hoaxes “generated by the opposition, '
        'for purposes of destroying our Country.” On Saturday, he continued '
        "his remarks on social media."
    )
    summary = build_summary(text, max_sentences=1)
    assert summary == (
        'He said these concerns are hoaxes “generated by the opposition, '
        'for purposes of destroying our Country.”'
    )
    assert "On Saturday" not in summary


ARTICLE = (
    "The company announced a major new model today. "
    "It supports twice the context length of its predecessor, reaching 256,000 tokens. "
    "Early benchmarks show a 12 percent gain on reasoning tasks, according to the lab. "
    "Pricing will be announced next quarter for enterprise customers in the United States."
)


def test_generate_script_starts_with_headline_then_source_sentences():
    result = generate_script(title="  Big AI News  ", raw_summary=ARTICLE)
    assert result["headline"] == "Big AI News"
    assert result["script_text"].startswith("Big AI News. ")
    assert result["summary"] and result["script_text"].endswith(result["summary"])
    assert result["briefing"]["sufficiency"] in ("sufficient", "thin")


def test_generate_script_never_invents_text_not_in_the_source():
    result = generate_script(title="Big AI News", raw_summary=ARTICLE)
    for sentence in result["summary"].split(". "):
        assert sentence.strip(". ")[:30] in ARTICLE


def test_generate_script_normalizes_whitespace():
    messy = ARTICLE.replace(". ", ".\n\n").replace("model", "model  ")
    result = generate_script(title="Title", raw_summary=messy)
    assert "\n" not in result["script_text"]
    assert "  " not in result["script_text"]


def test_generate_script_thin_teaser_returns_no_script_instead_of_padding():
    result = generate_script(title="Big AI News", raw_summary="Something happened.")
    assert result["script_text"] == ""
    assert result["briefing"]["sufficiency"] == "insufficient"
    assert "insufficient" in result["briefing"]["reason"]


def test_generate_script_no_source_at_all_returns_no_script():
    result = generate_script(title="Title", raw_summary=None, raw_content=None)
    assert result["script_text"] == ""
    assert result["headline"] == "Title"


def test_generate_script_prefers_raw_content_over_raw_summary():
    result = generate_script(
        title="Big AI News",
        raw_summary="A thin RSS excerpt that gets cut off [...]",
        raw_content=ARTICLE,
    )
    assert "thin RSS excerpt" not in result["script_text"]
    assert result["headline"] == "Big AI News"
    assert result["script_text"]


def test_generate_script_falls_back_to_raw_summary_when_raw_content_is_blank():
    """An empty/whitespace-only raw_content must not be mistaken for real content."""
    for blank in (None, "   "):
        result = generate_script(title="Title", raw_summary=ARTICLE, raw_content=blank)
        assert result["script_text"].startswith("Title. ")


def test_full_article_body_gets_hygiene_and_a_bounded_body():
    article_body = (
        "<p>The company announced a major new model today.</p> "
        "It supports twice the context length of its predecessor, reaching 256,000 tokens. "
        "Early benchmarks show a 12 percent gain on reasoning tasks, according to the lab. "
        "Pricing will be announced next quarter for customers in the United States. "
        "Subscribe to our newsletter for the full breakdown."
    )
    result = generate_script(title="Title", raw_summary="short excerpt", raw_content=article_body)
    assert "<p>" not in result["script_text"]
    assert "newsletter" not in result["script_text"].lower()
    assert result["briefing"]["sentence_count"] <= 5
